#SPDX-License-Identifier: MIT-0
---
- name: "Pull image"
  community.docker.docker_image_pull:
    name: sepehrmdn/nginx_hello

- name: "Start container"
  community.docker.docker_container:
    detach: true
    image: sepehrmdn/nginx_hello
    name: nginx_1
    output_logs: true
    state: started
    published_ports:
      - 8181:80
    cleanup: true
    restart_policy: always
    
- name: Show output
  ansible.builtin.debug:
    msg:  "The container nginx_1 is running on port 8181 and mapped to port 80 inside the container."